spring:
  #配置数据源信息
  datasource:
    #配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    #配置连接数据库的各个信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://121.43.53.31:3306/mapdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/online_class?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: zfx666
  thymeleaf:
    content-type: text/html
    cache: false
    mode: LEGACYHTML5
  #设置文件大小限制
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #配置类型别名所对应的包
    type-aliases-package: com.graduation.onlineclass.entity


server:
  port: 8080

loginurl: http://localhost:8080/swagger-ui.html
chormpath: C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe
edgepath: C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe
#文件路径
filepath: C:\\Users\\86182\\Desktop\\小程序文件资源\\文件\\

